[phases.setup]
nixPkgs = ["ffmpeg", "python311", "postgresql", "zlib", "libjpeg", "libpng", "libwebp"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements/production.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120"